### ISSUE TITLE
Line numbers misaligned

### ISSUE THREAD

**Issue by davwheat** [JoeGandy/ShareX-Custom-Upload#111] opened 2020-08-31 23:22 UTC
It seems the line numbers for text uploads have become misaligned during style changes. (Also highlighting has stopped working?)

[![](https://u.davwheat.dev/c0MlVQ.png)](https://u.davwheat.dev/PwzTYE.js)

**Comment by theaquarium** [comment] 2020-09-10 13:55
I'm not entirely sure what the issue is here. The CSS just seems to not work because it doesn't match what's in the repo. In @davwheat's CSS file, the `padding-top: 30px` line is before the `padding: 0 12px` so it gets overridden. @JoeGandy, if you can review the automatic updater PR, I can release a new version of the uploader which fixes a bunch of bugs and it should fix this.

**Comment by theaquarium** [comment] 2020-10-21 17:49
Fixed by #105 I believe.

**Closed by theaquarium** 2020-10-21 17:49 UTC
Labels: bug
